<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Indiekost_fas fa-fw fa-tachometer-alt</name>
   <tag></tag>
   <elementGuidId>aca0dc8b-70d7-487f-addf-8492878333d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='accordionSidebar']/li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-fw.fa-tachometer-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>22d28005-9849-4868-b8a1-e9e434972a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-fw fa-tachometer-alt</value>
      <webElementGuid>efd2f3ee-95ec-4d68-ba81-3dcf34fb6d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionSidebar&quot;)/li[@class=&quot;nav-item active&quot;]/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-fw fa-tachometer-alt&quot;]</value>
      <webElementGuid>bf3589d2-a5da-4641-ba0a-1de5f5ec2342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='accordionSidebar']/li/a/i</value>
      <webElementGuid>a90a5c04-e3a8-48aa-a01f-b4d1f57ed92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>8385fade-08fa-4b79-bc6e-96267cad4ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
