<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BERGABUNG</name>
   <tag></tag>
   <elementGuidId>13d8f8ea-9c35-4e6a-8f7c-7f9cf29e72b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BERGABUNG')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-gradient-big.mb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BERGABUNG&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>461e9509-026d-4fdd-98d6-bade04e721ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.whatsapp.com/send?phone=6281314270616</value>
      <webElementGuid>2362a4f1-26bb-47ab-a865-35d8ac04bd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5392f4db-2fd4-4c02-909e-88cd4d86ae69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-gradient-big mb-5</value>
      <webElementGuid>bef948d7-607b-4a5d-9686-100e8cb3df7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BERGABUNG</value>
      <webElementGuid>7f571cfb-7056-4156-92a7-80de9d13fa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/a[@class=&quot;btn btn-gradient-big mb-5&quot;]</value>
      <webElementGuid>06d85cb6-5a92-4810-93eb-615776fa9932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BERGABUNG')]</value>
      <webElementGuid>cbc644e3-2596-41f0-b271-ef2d04a7619a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BERGABUNG DENGAN DENSUKOST SEKARANG'])[1]/following::a[1]</value>
      <webElementGuid>1d2d0f23-fad5-4ae2-afff-3fe20cdee926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudah digunakan'])[1]/following::a[1]</value>
      <webElementGuid>999b33a6-9f90-42a0-8b6a-0220f788f147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa itu DENSUKOST?'])[1]/preceding::a[1]</value>
      <webElementGuid>719c4ab0-a54f-44b7-84c7-f563425cb21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa Rumah Densu Kost Bergabung?'])[1]/preceding::a[1]</value>
      <webElementGuid>2d45742b-831b-4207-9bd2-1a77b3de9949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BERGABUNG']/parent::*</value>
      <webElementGuid>8f941902-335b-45f7-9038-020adb4559b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://api.whatsapp.com/send?phone=6281314270616')]</value>
      <webElementGuid>f55b873c-cdab-4692-8d59-19c867b7a207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>43711d2a-3a5b-4cba-b563-d9387b5c8276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://api.whatsapp.com/send?phone=6281314270616' and (text() = 'BERGABUNG' or . = 'BERGABUNG')]</value>
      <webElementGuid>a437f64d-9d77-47ec-9a90-2499cb727ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
