<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tentang_navbar-toggler-icon</name>
   <tag></tag>
   <elementGuidId>96bc7b80-192d-46af-87d8-8cfa95a8131c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navbar-toggler-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Toggle navigation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4f5602e-0ebf-4acb-938f-d2b15d53bd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggler-icon</value>
      <webElementGuid>b1e7ac3d-faef-4446-9f7d-638b07b6ae20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container&quot;]/button[@class=&quot;navbar-toggler collapsed&quot;]/span[@class=&quot;navbar-toggler-icon&quot;]</value>
      <webElementGuid>aaeec458-26d3-4e88-b752-d3235522c4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/button/span</value>
      <webElementGuid>7db42aa1-0105-49f4-8515-a2190ff79fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>bb35fa11-6359-4e56-a43f-74ace90e6540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
